eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: subject
words: Hunter, Monster

---
spring:
  profiles: verb
words: shoot, killed, stroke

---
spring:
  profiles: article
words: a, the

---
spring:
  profiles: adjective
words: big, little

---
spring:
  profiles: noun
words: Villian, Zombie

