eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: subject
words: Hunter, Monster

---
spring:
  profiles: verb
words: shoot, killed, stroke

---
spring:
  profiles: article
words: a, the

---
spring:
  profiles: adjective
words: big, little

---
spring:
  profiles: noun
words: Villian, Zombie

